name: parkfinder_customer
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  english_words: ^4.0.0
  flutter_svg: ^2.0.9 
  http: ^0.13.6
  logger: ^2.0.1
  google_maps_flutter: ^2.4.0
  url_launcher: ^6.2.2
  geolocator: ^10.0.0
  material_floating_search_bar_2: ^0.5.0
  geocoding: ^2.1.0
  flutter_secure_storage: ^9.0.0
  qr_code_scanner: ^1.0.1
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  socket_io_client: 1.0.1
  logging: ^1.2.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  fl_chart: ^0.40.0
  flutter_easyloading: ^3.0.5

  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/icons/
    - lib/assets/images/
    - lib/.env

  fonts: 
    - family: Sukhumvit
      fonts:
        - asset: lib/assets/fonts/SukhumvitSet-Bold.ttf
          weight: 800
        - asset: lib/assets/fonts/SukhumvitSet-SemiBold.ttf
          weight: 700
        - asset: lib/assets/fonts/SukhumvitSet-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/SukhumvitSet-Thin.ttf
          weight: 400
        - asset: lib/assets/fonts/SukhumvitSet-Light.ttf
          weight: 300